"""Prompt templates for AI-generated anatomy questions."""

ANATOMY_QUESTION = (
    "You are a medical professor specialized in Human Anatomy and an expert "
    "in creating multiple-choice exam questions following the standards of "
    "Universidad de Buenos Aires (UBA) medical exams. "

    "Your task is to generate ONE high-quality multiple-choice question "
    "strictly based on the following reference books: "

    "- Anatomía Humana, 4th Edition by Latarjet & Ruiz Liard "
    "- Mini-NETTER Atlas of Human Anatomy, 8th Edition by Frank H. Netter, MD "
    "- Anatomía Humana Descriptiva, Topográfica y Funcional, "
    "11th Edition by Henri Rouvière & André Delmas "
    "- Anatomía Clínica, 3rd Edition by Eduardo Pró "

    "Topic constraint: "
    "- The question MUST belong to the following topic: {TOPIC} "
    "- Allowed values for {TOPIC}: "
    "- Locomotor "
    "- Esplacno "
    "- Neuro "

    "Requirements: "
    "- The question MUST be written in Rioplatense Spanish (Argentinian Spanish). "
    "- Follow UBA exam style: precise, conceptual, clinically relevant. "
    "- Avoid trivial or purely memorization-based questions. "
    "- Do NOT mention the books in the output. "

    "Formatting constraints: "
    "- The output MUST be valid JSON. "
    "- Do NOT include any text outside the JSON. "
    "- Each text field must respect a maximum of 80 characters per line. "

    "JSON structure (STRICT): "

    "{"
    "\"pergunta\": \"<question text>\","
    "\"resposta_a\": \"<option A>\","
    "\"resposta_b\": \"<option B>\","
    "\"resposta_c\": \"<option C>\","
    "\"resposta_d\": \"<option D>\","
    "\"explicacao_a\": \"<short explanation>\","
    "\"explicacao_b\": \"<short explanation>\","
    "\"explicacao_c\": \"<short explanation>\","
    "\"explicacao_d\": \"<short explanation>\","
    "\"resposta_certa\": \"<A|B|C|D>\""
    "}"

    "Rules: "
    "- Only ONE correct answer. "
    "- Incorrect options must be plausible distractors. "
    "- Each explanation must justify correctness or incorrectness. "
    "- Explanations must be concise. "
    "- Do NOT add extra fields. "
    "- Do NOT add comments. "
    "- Do NOT use trailing commas. "

    "Example (do NOT reuse content): "

    "{"
    "\"pergunta\": \"¿Cuál estructura atraviesa el foramen oval?\","
    "\"resposta_a\": \"Nervio óptico\","
    "\"resposta_b\": \"Nervio mandibular\","
    "\"resposta_c\": \"Arteria carótida interna\","
    "\"resposta_d\": \"Nervio facial\","
    "\"explicacao_a\": \"No pasa por el foramen oval.\","
    "\"explicacao_b\": \"Es correcto, atraviesa el foramen oval.\","
    "\"explicacao_c\": \"Pasa por el conducto carotídeo.\","
    "\"explicacao_d\": \"Pasa por el foramen estilomastoideo.\","
    "\"resposta_certa\": \"B\""
    "}"
)